// <auto-generated />
using System;
using DemoWinForms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoWinForms.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DemoWinForms.Domain.Entities.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("#808080");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Etiquetas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#DC3545",
                            Nombre = "Urgente"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#007BFF",
                            Nombre = "Proyecto"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#28A745",
                            Nombre = "Personal"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#FFC107",
                            Nombre = "Trabajo"
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#FF5733",
                            Nombre = "Importante"
                        });
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EliminadoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TareaPadreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EliminadoLogico");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("Prioridad");

                    b.HasIndex("TareaPadreId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tareas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Personal",
                            Descripcion = "Esta es tu primera tarea de ejemplo. Puedes editarla o eliminarla.",
                            EliminadoLogico = false,
                            Estado = 1,
                            FechaCreacion = new DateTime(2025, 11, 5, 12, 29, 43, 508, DateTimeKind.Local).AddTicks(5648),
                            FechaVencimiento = new DateTime(2025, 11, 12, 12, 29, 43, 508, DateTimeKind.Local).AddTicks(5649),
                            Prioridad = 2,
                            Titulo = "Bienvenido al Gestor de Tareas",
                            UltimaModificacion = new DateTime(2025, 11, 5, 12, 29, 43, 508, DateTimeKind.Local).AddTicks(5657),
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.TareaEtiqueta", b =>
                {
                    b.Property<int>("TareaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EtiquetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TareaId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("TareasEtiquetas", (string)null);
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TaskListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("TaskListId");

                    b.ToTable("TaskItems", (string)null);
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.TaskList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("TaskLists", (string)null);
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Edad = 30,
                            Email = "demo@tareas.com",
                            Nombre = "Usuario Demo",
                            Pais = "España",
                            Telefono = "123456789"
                        });
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.Tarea", b =>
                {
                    b.HasOne("DemoWinForms.Domain.Entities.Tarea", "TareaPadre")
                        .WithMany("Subtareas")
                        .HasForeignKey("TareaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DemoWinForms.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TareaPadre");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.TareaEtiqueta", b =>
                {
                    b.HasOne("DemoWinForms.Domain.Entities.Etiqueta", "Etiqueta")
                        .WithMany("TareaEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DemoWinForms.Domain.Entities.Tarea", "Tarea")
                        .WithMany("TareaEtiquetas")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("DemoWinForms.Domain.Entities.TaskList", "TaskList")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskList");
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.Etiqueta", b =>
                {
                    b.Navigation("TareaEtiquetas");
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.Tarea", b =>
                {
                    b.Navigation("Subtareas");

                    b.Navigation("TareaEtiquetas");
                });

            modelBuilder.Entity("DemoWinForms.Domain.Entities.TaskList", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
